version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD:
      DB_DATABASE: coderlab
      PORT: 4000
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost
      REACT_APP_API_PORT: 4000
      PORT: 3000
    depends_on:
      - backend

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: coderlab
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"